apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    name: demo
spec:
  type: {{ svc.demo.balancer }}
  ports:
    # the port that this service should serve on
    - port: {{ svc.demo.port }}
  selector:
    name: update-demo
