apiVersion: v1
kind: ReplicationController
metadata:
  name: update-demo
spec:
  selector:
    name: update-demo
  template:
    metadata:
      labels:
        name: update-demo
    spec:
      replicas: {{ rc.demo.replicas }}
      containers:
      - image: gcr.io/google_containers/update-demo:kitten
        name: update-demo
        ports:
        - containerPort: 80
          protocol: TCP
